"""Lucide icons shipped in static/vendor/lucide/icons.svg (redesign R4a).

One icon set only (UI-GUIDELINES). To add an icon: put its Lucide name here,
then run ``python scripts/build_icon_sprite.py <path to lucide-static package>``.
"""

from __future__ import annotations

ICON_SPRITE = "vendor/lucide/icons.svg"

ICON_NAMES: frozenset[str] = frozenset(
    {
        "arrow-left",
        "banknote",
        "bell",
        "book",
        "book-open",
        "building-2",
        "calculator",
        "calendar",
        "calendar-check",
        "calendar-days",
        "calendar-plus",
        "chart-bar",
        "chart-column",
        "chart-line",
        "chart-pie",
        "check",
        "chevron-down",
        "chevron-left",
        "chevron-right",
        "circle-alert",
        "circle-check",
        "circle-pause",
        "clipboard",
        "clipboard-check",
        "clipboard-list",
        "clock",
        "coins",
        "credit-card",
        "door-open",
        "download",
        "ellipsis",
        "eye",
        "eye-off",
        "file",
        "file-pen-line",
        "file-plus",
        "file-text",
        "filter",
        "folder-open",
        "gauge",
        "graduation-cap",
        "hand-coins",
        "history",
        "house",
        "inbox",
        "info",
        "key-round",
        "layers",
        "link",
        "list",
        "list-checks",
        "lock",
        "lock-keyhole",
        "log-out",
        "mail",
        "menu",
        "monitor",
        "palette",
        "pencil",
        "phone",
        "plus",
        "presentation",
        "receipt",
        "receipt-text",
        "school",
        "search",
        "send",
        "settings",
        "shield-check",
        "sliders-horizontal",
        "square-pen",
        "triangle-alert",
        "upload",
        "user",
        "user-check",
        "user-cog",
        "user-plus",
        "user-round",
        "users",
        "users-round",
        "video",
        "x",
    }
)
