# Generated by Django 5.2.17 on 2026-10-06 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_hash_set_password_token_keys"),
        ("accounts", "0003_user_phone"),
    ]

    operations = []
