# Generated by Django 5.2.17 on 2026-10-08 15:00

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_lowercase_emails"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("institutes", "0004_fix_basic_plan_features"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="accounts_user_email_lower_unique",
            ),
        ),
    ]
