# Generated by Django 5.2.17 on 2026-10-07 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0001_initial"),
        ("people", "0002_guardianstudentlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="class_label",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="academics.classlabel",
            ),
        ),
    ]
