# Generated by Django 5.2.17 on 2026-10-08 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutes", "0004_fix_basic_plan_features"),
        ("people", "0003_studentprofile_class_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalAccessRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blocked", models.BooleanField(default=False)),
                ("exempt", models.BooleanField(default=False)),
                ("changed_at", models.DateTimeField(auto_now=True)),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="institutes.institute",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_rule",
                        to="people.studentprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
