# Generated by Django 5.2.17 on 2026-10-05 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("institutes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantProbe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=64)),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="institutes.institute",
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
            },
        ),
    ]
