# Generated by Django 5.2.17 on 2026-10-05 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutes", "0001_initial"),
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantprobe",
            name="institute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="institutes.institute",
            ),
        ),
    ]
